### ISSUE TITLE
wss 'connection' event not firing

### ISSUE THREAD

**Issue by jamiemarkwhite** [talentlessguy/tinyws#2]
Hi, thanks for your work on this. I ran into an issue with setting up ws heartbeat (following the ws lib example in their docs). It seems that you need to emit the wss 'connection' event in the handleUpgrade callback. (Well, this seemed to solve it for me anyway! I dug into the ws lib code and they did the same). Hope this is a useful. 🙂

```
wss.handleUpgrade(req, req.socket, Buffer.alloc(0), (ws) => {
  wss.emit('connection', ws, req);
  resolve(ws);
});
```

**Comment by talentlessguy** [comment]
could you please PR this fix?
