### ISSUE TITLE
How to get websocket server access?

### ISSUE THREAD

**Issue by reesericci** [talentlessguy/tinyws#6]
Is there a method for accessing the websocket server?

**Comment by talentlessguy** [comment]
https://github.com/tinyhttp/tinyws/blob/e91c40cda7ef91a6bf6c08d6742531bcd94d1d39/tests/index.test.ts#L116-L132

**Comment by go4cas** [comment]
@talentlessguy ... I have implemented as you recommended, but I am not sure how to access the`wss` instance from within a handler? Any suggestions?

**Comment by talentlessguy** [comment]
@go4cas wss here has a global scope so you can just use it within a handler as any other variable

```js
app.use((req, res) => {
//  wss.something
})
```
